plugins {
	id 'com.axelor.app'
}

apply from: "../libs.gradle"
apply from: "../version.gradle"

apply {
	version = openSuiteVersion
}

axelor {
	title "Axelor Dictionary"
	description "Axelor Dictionary Module for Country and Currency Management"
}

dependencies {
	api project(":modules:axelor-base")
}
