################################################################################
#
# Application Configuration
#
################################################################################

# Database settings
# ~~~~~
db.default.driver = org.postgresql.Driver
db.default.ddl = update
db.default.url = jdbc:postgresql://localhost:5432/axelor
db.default.user = postgres
db.default.password = 5555

# Shared cache mode settings (ALL, DISABLE_SELECTIVE, ENABLE_SELECTIVE, NONE)
jakarta.persistence.sharedCache.mode = ENABLE_SELECTIVE

# HikariCP connection pool
hibernate.hikari.minimumIdle = 5
hibernate.hikari.maximumPoolSize = 20
hibernate.hikari.idleTimeout = 300000

# Application Information
# ~~~~~
application.name = Axelor Open Suite
application.description = Axelor Entreprise Application
application.version = 9.0.6
application.author = Axelor
application.copyright = Copyright (c) {year} Axelor. All Rights Reserved.

# Header logo. Should be 40px in height with transparent background.
application.logo = img/axelor.png

# Home website. Link to be used with header logo.
application.home = https://www.axelor.com

# Online help. Link to be used in About page.
application.help = https://docs.axelor.com/abs/latest/functional/index.html

# Application deployment mode. Can be `prod` or `dev`
application.mode = dev

# CSS theme
application.theme = Modern

# Default Locale (en, fr, fr_FR, en_US)
application.locale = fr

# View configuration
# ~~~~~
view.max-tabs = 10

# Menu style (left, top, both)
view.menubar.location = both

# API
# ~~~~~
api.pagination.max-per-page = 100000

# Session configuration
# ~~~~~
session.timeout = 480

# Reports
# ~~~~~
reports.aos.use-embedded-engine =
reports.aos.external-engine =
reports.aos.resource-path =

# External directory for birt report designs
reports.design-dir = {user.home}/data/reports

# Custom fonts config path for birt report designs
reports.fonts-config = fonts/ReportFonts.xml

# Encryption
# ~~~~~
encryption.password = MySuperSecretKey
encryption.bankorder.password = BankOrderEncryptionKey
encryption.algorithm = CBC

# Data
# ~~~~~

# Automatic import of BIRT templates
# data.import.init-data = \
#  modules/axelor-open-suite/axelor-dictionary/src/main/resources/data/birt-templates.xml

# Storage path for upload files (attachments)
#data.upload.dir = {java.io.tmpdir}/axelor-files
#data.upload.temp-dir = {java.io.tmpdir}/axelor-temps
#data.upload.max-size = 5

data.upload.dir = C:/Users/Lenovo/Documents/MyMetaFiles
data.upload.filename-pattern = {year}/{month}/{day}/{name}
data.upload.max-size = 10
data.upload.temp-dir = {java.io.tmpdir}/axelor-temps

# Data export encoding
data.export.encoding = UTF-8

# Whether to import demo data for the application
data.import.demo-data = false

# Context values
# ~~~~~
context.appLogo = com.axelor.apps.base.service.user.UserService:getUserActiveCompanyLogoLink
context.app = com.axelor.studio.app.service.ScriptAppService

# Logging
# ~~~~~
logging.level.root = ERROR
logging.level.com.axelor = DEBUG

# AOS Properties
# ~~~~~
context.date = com.axelor.apps.base.service.DateService:date
utils.api.enable = true
# ????????? ??? ?????? ???? ?????? (??????????? ????????)
second.db.url = jdbc:postgresql://localhost:5432/external_logs
second.db.user = postgres
second.db.password = 5555
